# sql-admin (Adminer)
server {
    listen 80;
    server_name sql-admin.local-env.com;
    location / {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $upstream http://sql-admin:8080;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
server {
    listen 443 ssl;
    server_name sql-admin.local-env.com;
    ssl_certificate /etc/nginx/certs/live/local-env.com/cert.pem;
    ssl_certificate_key /etc/nginx/certs/live/local-env.com/key.pem;
    location / {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $upstream http://sql-admin:8080;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
