# Trigger de generacion de certificado wildcard para local-env.com
# Los proxies de servicios opcionales se gestionan via Makefile en http/services/

server {
    listen 80;
    server_name dashboard.local-env.com;
    location / {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $upstream http://dashboard:8000;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}

server {
    listen 443 ssl;
    server_name dashboard.local-env.com;
    ssl_certificate /etc/nginx/certs/live/local-env.com/cert.pem;
    ssl_certificate_key /etc/nginx/certs/live/local-env.com/key.pem;
    location / {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $upstream http://dashboard:8000;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
